"""Fix column

Revision ID: 8c098361de71
Revises: 1a632f73ade1
Create Date: 2024-08-08 13:07:30.646170

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision: str = "8c098361de71"
down_revision: Union[str, None] = "1a632f73ade1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("films", sa.Column("json_data", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("films", "json_data")
    # ### end Alembic commands ###
