"""Fix column

Revision ID: 1a632f73ade1
Revises: 946caa7aef5d
Create Date: 2024-08-08 13:00:59.627578

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op  # type: ignore

# revision identifiers, used by Alembic.
revision: str = "1a632f73ade1"
down_revision: Union[str, None] = "946caa7aef5d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "episodes",
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("season", sa.Integer(), nullable=False),
        sa.Column("episode", sa.Integer(), nullable=False),
        sa.Column("file_path", sa.String(), nullable=False),
        sa.Column("picture_path", sa.String(), nullable=False),
        sa.Column("film_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["film_id"], ["films.id"], name=op.f("fk_episodes_film_id_films")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_episodes")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("episodes")
    # ### end Alembic commands ###
