"""Added kinopub models

Revision ID: b72a6c2bee2b
Revises: 58011a5cb0bf
Create Date: 2024-07-10 23:33:37.149743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b72a6c2bee2b'
down_revision: Union[str, None] = '58011a5cb0bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_film_association',
    sa.Column('film_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_category_film_association_category_id_categories')),
    sa.ForeignKeyConstraint(['film_id'], ['films.id'], name=op.f('fk_category_film_association_film_id_films')),
    sa.PrimaryKeyConstraint('film_id', 'category_id', name=op.f('pk_category_film_association'))
    )
    op.add_column('films', sa.Column('rating', sa.DECIMAL(precision=2, scale=1), nullable=False))
    op.add_column('films', sa.Column('file_path', sa.String(), nullable=False))
    op.add_column('films', sa.Column('picture_path', sa.String(), nullable=False))
    op.drop_constraint('fk_films_category_id_categories', 'films', type_='foreignkey')
    op.drop_column('films', 'category_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('films', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('fk_films_category_id_categories', 'films', 'categories', ['category_id'], ['id'])
    op.drop_column('films', 'picture_path')
    op.drop_column('films', 'file_path')
    op.drop_column('films', 'rating')
    op.drop_table('category_film_association')
    # ### end Alembic commands ###
